#!/usr/bin/env python3
"""Regenerate vault/40-codebase-map/Candidates.md from the notes' frontmatter."""
import re
from pathlib import Path
d = Path(__file__).resolve().parents[1] / "vault/40-codebase-map"
order = {"T": 0, "B": 1, "O": 2, "S": 3, "P": 4, "L": 5}
rows = []
for p in d.glob("*.md"):
    if p.name == "Candidates.md":
        continue
    fm = dict(re.findall(r"^(\w+): (.*)$", p.read_text().split("---")[1], re.M))
    title = p.stem.split(" ", 1)[1]
    rows.append((order.get(fm["id"][0], 9), int(re.sub(r"\D", "", fm["id"]) or 0),
                 f"| [[{p.stem}\\|{fm['id']}]] | {title} | {fm['area']} | {fm['effort']} | {fm['gate']} | "
                 f"{fm.get('profiled_share', 'null')} | {fm['status']} |"))
rows.sort()
(d / "Candidates.md").write_text(
    "# Candidates\n\nStatus lifecycle: `candidate → profiled → branch → gated → accepted | rejected | dropped`.\n"
    "Generated by `scripts/candidates-index.py` from each note's frontmatter; edit the notes, not this table.\n\n"
    "| id | title | area | effort | gate | profiled share | status |\n|---|---|---|---|---|---|---|\n"
    + "\n".join(r[2] for r in rows)
    + "\n\nNot performance, report only: `HighsCliqueTable.cpp:~1763` has `exit(0);` in an unused `separateCliques` overload.\n")
print(len(rows), "candidates")
